[package]
name = "async-call-raw-set-storage"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = ["elrond-wasm-node"]

[dependencies.first-contract-async]
path = "first-contract-async"

[dependencies.second-contract-async]
path = "second-contract-async"

[dependencies.elrond-wasm]
version = "0.12.0"
path = "../../../elrond-wasm"

[dependencies.elrond-wasm-derive]
version = "0.12.0"
path = "../../../elrond-wasm-derive"

[dependencies.elrond-wasm-node]
version = "0.12.0"
path = "../../../elrond-wasm-node"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.12.0"
path = "../../../elrond-wasm-debug"
